version: "3"

vars:
  NAME: "tgnotifier"

tasks:
  default:
    - task: build

  build-matrix:
    vars:
      USER_CONFIG: '{{ default "" .USER_CONFIG }}'
      GLOBAL_CONFIG: '{{ default "" .GLOBAL_CONFIG }}'
      VERSION: '{{ default "" .VERSION }}'
      MATRIX:
        - { OS: "linux", ARCH: "amd64" }
        - { OS: "linux", ARCH: "arm" }
        - { OS: "linux", ARCH: "arm64" }
        - { OS: "darwin", ARCH: "amd64" }
        - { OS: "darwin", ARCH: "arm64" }
        - { OS: "windows", ARCH: "amd64" }
    cmds:
      - for: { var: MATRIX }
        cmd: |
          CGO_ENABLED=0 GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} go build \
            -ldflags="-X 'github.com/religiosa1/tgnotifier/internal/cmd.version={{ .VERSION }}'{{if .USER_CONFIG}} \
              -X 'github.com/religiosa1/tgnotifier/internal/config.UserConfigPath={{ .USER_CONFIG }}'{{end}}{{if .GLOBAL_CONFIG}} \
              -X 'github.com/religiosa1/tgnotifier/internal/config.GlobalConfigPath={{ .GLOBAL_CONFIG }}'{{end}}" \
            -o build/{{ .NAME }}-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}{{if eq .ITEM.OS "windows"}}.exe{{end}} \
            'github.com/religiosa1/{{ .NAME }}/cmd/{{ .NAME }}'

  build:
    vars:
      USER_CONFIG: '{{ default "" .USER_CONFIG }}'
      GLOBAL_CONFIG: '{{ default "" .GLOBAL_CONFIG }}'
      VERSION: '{{ default "" .VERSION }}'
    cmd: |
      CGO_ENABLED=0 go build \
        -ldflags="-X 'github.com/religiosa1/tgnotifier/internal/cmd.version={{ .VERSION }}'{{if .USER_CONFIG}} \
          -X 'github.com/religiosa1/tgnotifier/internal/config.UserConfigPath={{ .USER_CONFIG }}'{{end}}{{if .GLOBAL_CONFIG}} \
          -X 'github.com/religiosa1/tgnotifier/internal/config.GlobalConfigPath={{ .GLOBAL_CONFIG }}'{{end}}" \
        'github.com/religiosa1/{{ .NAME }}/cmd/{{ .NAME }}'

  test:
    cmds:
      - go test ./...

  clean:
    cmds:
      - rm -rf build
